name: CI/CD Pipeline - ML API

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PROJECT_ID: graphite-byte-472516-n8
  REGION: us-central1
  REPO_NAME: ml-repo
  IMAGE_NAME: ml-api
  SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}

jobs:
  # Job 1: Testes unitários
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

  # Job 2: Build e Push Docker
  docker:
    runs-on: ubuntu-latest
    needs: test  # roda apenas se os testes passarem
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ env.PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Configure Docker
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and tag Docker image
        run: |
          VERSION=$(date +%Y.%m.%d.%H%M)
          docker build -t ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$VERSION .
          docker tag ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$VERSION \
                     ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Push Docker image
        run: |
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:$VERSION
          docker push ${{ env.REGION }}-docker.pkg.dev/${{ env.PROJECT_ID }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}:latest

  # Job 3: Terraform Apply
  terraform:
    runs-on: ubuntu-latest
    needs: docker  # roda apenas se Docker push for bem-sucedido
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.6.0

      - name: Terraform Init
        run: terraform -chdir=terraform init

      - name: Terraform Apply
        run: terraform -chdir=terraform apply -auto-approve

  # Job 4: Notificação Slack
  slack-notify:
    runs-on: ubuntu-latest
    needs: [test, docker, terraform]
    steps:
      - name: Send Slack notification
        if: ${{ always() }}
        run: |
          STATUS="SUCCESS"
          if [ "${{ job.status }}" != "success" ]; then
            STATUS="FAILED"
          fi
          curl -X POST -H 'Content-type: application/json' \
               --data "{\"text\":\"CI/CD Pipeline - ML API finished with status: $STATUS\"}" \
               ${{ env.SLACK_WEBHOOK }}
